import type { SourceLine } from "@/types/visualization";
import type { EventLoopStep } from "./types";

export const CODE_LINES: SourceLine[] = [
  { num: 1, text: "console.log('Start');" },
  { num: 2, text: "" },
  { num: 3, text: "setTimeout(() => {" },
  { num: 4, text: "  console.log('Timeout');" },
  { num: 5, text: "}, 0);" },
  { num: 6, text: "" },
  { num: 7, text: "Promise.resolve()" },
  { num: 8, text: "  .then(() => {" },
  { num: 9, text: "    console.log('Promise 1');" },
  { num: 10, text: "  })" },
  { num: 11, text: "  .then(() => {" },
  { num: 12, text: "    console.log('Promise 2');" },
  { num: 13, text: "  });" },
  { num: 14, text: "" },
  { num: 15, text: "console.log('End');" },
];

export const STEPS: EventLoopStep[] = [
  {
    descriptionHtml:
      `<span class="hl-stack">Call Stack</span> receives <code>console.log('Start')</code> and executes immediately.`,
    activeLine: 1,
    doneLines: [],
    stack: ["console.log('Start')"],
    webApis: [],
    taskQueue: [],
    microtaskQueue: [],
    consoleOutput: ["Start"],
    loopActive: false,
    loopLabel: "idle",
  },
  {
    descriptionHtml:
      `<code>console.log('Start')</code> pops from the <span class="hl-stack">Call Stack</span>. Output: <strong>Start</strong>.`,
    activeLine: 1,
    doneLines: [1],
    stack: [],
    webApis: [],
    taskQueue: [],
    microtaskQueue: [],
    consoleOutput: ["Start"],
    loopActive: false,
    loopLabel: "idle",
  },
  {
    descriptionHtml:
      `<code>setTimeout(cb, 0)</code> is pushed to the <span class="hl-stack">Call Stack</span>.`,
    activeLine: 3,
    doneLines: [1],
    stack: ["setTimeout(cb, 0)"],
    webApis: [],
    taskQueue: [],
    microtaskQueue: [],
    consoleOutput: ["Start"],
    loopActive: false,
    loopLabel: "idle",
  },
  {
    descriptionHtml:
      `<code>setTimeout</code> delegates to <span class="hl-api">Web APIs</span>, and a timer starts.`,
    activeLine: 3,
    doneLines: [1, 3, 4, 5],
    stack: [],
    webApis: ["Timer (0ms)"],
    taskQueue: [],
    microtaskQueue: [],
    consoleOutput: ["Start"],
    loopActive: false,
    loopLabel: "idle",
  },
  {
    descriptionHtml:
      `Timer completes, so callback moves into the <span class="hl-task">Task Queue</span>.`,
    activeLine: null,
    doneLines: [1, 3, 4, 5],
    stack: [],
    webApis: [],
    taskQueue: ["() => log('Timeout')"],
    microtaskQueue: [],
    consoleOutput: ["Start"],
    loopActive: false,
    loopLabel: "idle",
  },
  {
    descriptionHtml:
      `<code>Promise.resolve().then(cb)</code> is pushed to the <span class="hl-stack">Call Stack</span>.`,
    activeLine: 7,
    doneLines: [1, 3, 4, 5],
    stack: ["Promise.resolve().then(cb)"],
    webApis: [],
    taskQueue: ["() => log('Timeout')"],
    microtaskQueue: [],
    consoleOutput: ["Start"],
    loopActive: false,
    loopLabel: "idle",
  },
  {
    descriptionHtml:
      `Promise resolves and the callback enters the <span class="hl-micro">Microtask Queue</span> (higher priority).`,
    activeLine: 8,
    doneLines: [1, 3, 4, 5, 7, 8, 9, 10, 11, 12, 13],
    stack: [],
    webApis: [],
    taskQueue: ["() => log('Timeout')"],
    microtaskQueue: ["() => log('Promise 1')"],
    consoleOutput: ["Start"],
    loopActive: false,
    loopLabel: "idle",
  },
  {
    descriptionHtml:
      `<code>console.log('End')</code> is still synchronous and executes before queued callbacks.`,
    activeLine: 15,
    doneLines: [1, 3, 4, 5, 7, 8, 9, 10, 11, 12, 13],
    stack: ["console.log('End')"],
    webApis: [],
    taskQueue: ["() => log('Timeout')"],
    microtaskQueue: ["() => log('Promise 1')"],
    consoleOutput: ["Start"],
    loopActive: false,
    loopLabel: "idle",
  },
  {
    descriptionHtml:
      `<code>console.log('End')</code> finishes. Sync code is done and output now includes <strong>End</strong>.`,
    activeLine: 15,
    doneLines: [1, 3, 4, 5, 7, 8, 9, 10, 11, 12, 13, 15],
    stack: [],
    webApis: [],
    taskQueue: ["() => log('Timeout')"],
    microtaskQueue: ["() => log('Promise 1')"],
    consoleOutput: ["Start", "End"],
    loopActive: false,
    loopLabel: "idle",
  },
  {
    descriptionHtml:
      `<span class="hl-loop">Event Loop</span> checks queues: <span class="hl-micro">Microtasks</span> are always consumed first.`,
    activeLine: null,
    doneLines: [1, 3, 4, 5, 7, 8, 9, 10, 11, 12, 13, 15],
    stack: [],
    webApis: [],
    taskQueue: ["() => log('Timeout')"],
    microtaskQueue: ["() => log('Promise 1')"],
    consoleOutput: ["Start", "End"],
    loopActive: true,
    loopLabel: "checking",
  },
  {
    descriptionHtml:
      `<span class="hl-loop">Event Loop</span> moves the first microtask to the <span class="hl-stack">Call Stack</span>.`,
    activeLine: 9,
    doneLines: [1, 3, 5, 7, 8, 10, 11, 12, 13, 15],
    stack: ["() => log('Promise 1')"],
    webApis: [],
    taskQueue: ["() => log('Timeout')"],
    microtaskQueue: [],
    consoleOutput: ["Start", "End", "Promise 1"],
    loopActive: true,
    loopLabel: "running",
  },
  {
    descriptionHtml:
      `Promise chaining queues another callback in the <span class="hl-micro">Microtask Queue</span>.`,
    activeLine: 11,
    doneLines: [1, 3, 5, 7, 8, 9, 10, 13, 15],
    stack: [],
    webApis: [],
    taskQueue: ["() => log('Timeout')"],
    microtaskQueue: ["() => log('Promise 2')"],
    consoleOutput: ["Start", "End", "Promise 1"],
    loopActive: true,
    loopLabel: "checking",
  },
  {
    descriptionHtml:
      `<span class="hl-loop">Event Loop</span> drains the remaining microtask and runs Promise 2 callback.`,
    activeLine: 12,
    doneLines: [1, 3, 5, 7, 8, 9, 10, 11, 13, 15],
    stack: ["() => log('Promise 2')"],
    webApis: [],
    taskQueue: ["() => log('Timeout')"],
    microtaskQueue: [],
    consoleOutput: ["Start", "End", "Promise 1", "Promise 2"],
    loopActive: true,
    loopLabel: "running",
  },
  {
    descriptionHtml:
      `All microtasks are done, so the <span class="hl-loop">Event Loop</span> checks the <span class="hl-task">Task Queue</span>.`,
    activeLine: null,
    doneLines: [1, 3, 5, 7, 8, 9, 10, 11, 12, 13, 15],
    stack: [],
    webApis: [],
    taskQueue: ["() => log('Timeout')"],
    microtaskQueue: [],
    consoleOutput: ["Start", "End", "Promise 1", "Promise 2"],
    loopActive: true,
    loopLabel: "checking",
  },
  {
    descriptionHtml:
      `<span class="hl-loop">Event Loop</span> moves the timeout callback to the <span class="hl-stack">Call Stack</span>.`,
    activeLine: 4,
    doneLines: [1, 3, 5, 7, 8, 9, 10, 11, 12, 13, 15],
    stack: ["() => log('Timeout')"],
    webApis: [],
    taskQueue: [],
    microtaskQueue: [],
    consoleOutput: ["Start", "End", "Promise 1", "Promise 2", "Timeout"],
    loopActive: true,
    loopLabel: "running",
  },
  {
    descriptionHtml:
      `<strong>Done:</strong> output order is Start \u2192 End \u2192 Promise 1 \u2192 Promise 2 \u2192 Timeout.`,
    activeLine: null,
    doneLines: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
    stack: [],
    webApis: [],
    taskQueue: [],
    microtaskQueue: [],
    consoleOutput: ["Start", "End", "Promise 1", "Promise 2", "Timeout"],
    loopActive: false,
    loopLabel: "idle",
  },
];
